### ISSUE TITLE
create several user role

### ISSUE THREAD

**Issue by justmelnyc** [justmelnyc/booking#2]
We need to create several user roles, admin, the general user, and paid user. Should show a different user interface for the different user role.
For admins, schedule should be shown to user,
For general user, they should be able to book reservations"

**Comment by fortunes-technology** [comment]
@justmelnyc I have some question.
1. What's paid user
2. Should the schedule be shown to general user also?

**Comment by justmelnyc** [comment]
I'd like to keep 2 roles just for users, not admins, and keep track of them for a future feature of the service. like a subscription paid monthly, and one for one-time payment.

**Comment by justmelnyc** [comment]
no, users only get to book appointments.
